### ISSUE TITLE
Fix tile hitboxes on more organic structures 

### ISSUE THREAD

**Issue by NotLe0n** [bafto/Platformer#18]
See the unnecessary hitboxes? I think the system needs to be rewritten and made cleaner (I can't even read it)
![image](https://user-images.githubusercontent.com/26361108/108634505-14e02c80-747a-11eb-80f1-0951c5f9739c.png)

**Comment by bafto** [comment]
I'll look into it. The algorithm can definitely be written cleaner and more readable, though the algorithm itself should not be changed to still function with the collision, and if we want to have fewer hitboxes we would have to change the collision code as well (for example to ray-casting with a lot maths).

**Comment by bafto** [comment]
There is no bug. How the hitboxes are is how they're supposed to be. The algorithm takes care that for each ground and each ceiling there is only one smooth hitbox, and it does that good. Walls can be made of multiple hitboxes, because that won't affect the collision. There are no "unnecessary" hitboxes, thats just how the algorithm works. It is no problem if there are more hitboxes then there have to be, cause the "heavy" collision resolving only happens for those, an Entity collides with, thus the other ones just get ignored in the loop. Of course it looks a bit ugly in Debug, but there is no problem except for the readability of the MakeHitboxes function.

**Comment by bafto** [comment]
For a commented version of MakeHiboxes see fb6058e
